name: Build and Deploy Workflow

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main
    paths:
      - src/**

  push:
    branches:
      - main
    paths:
      - src/**

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install package
        run: npm ci

      - name: Run test
        run: npm run test

      - name: Run build
        run: npm run build

      - name: "Upload artifact"
        uses: actions/upload-artifact@v3
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        with:
          name: app
          path: |
            build/

  deploy-job:
    runs-on: ubuntu-latest
    needs: [build-job]
    if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
    environment: development
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: app

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3
        with:
          build_dir: .
          author: "Deploy Job"
          commit_message: "Github Page Deploy"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
